apiVersion: v1
kind: Service
metadata:
   name: eureka-service
   namespace: dr
spec:
   selector:
     labels:
       app: eureka-service
   ports:
     - protocol: TCP
       port: 80
       targetPort: 8761
   type: clusterIP
