# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-ipaddresspool 
  namespace: metallb-system
spec:
  addresses:
    - 10.10.1.8-10.10.1.15
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-l2advertisement 
  namespace: metallb-system
spec:
  ipAddressPools:
    - lb-ipaddresspool
